apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: hackathon-9nett
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'apis'
        static_configs:
          - targets:
              - donation-api:80
              - campaign-api:80