apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: hackathon-9nett
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: hackathondb
  MYSQL_USER: appuser
  MYSQL_PASSWORD: app123